### ISSUE TITLE
InertiaAffectsPitch not working

### ISSUE THREAD

**Issue by ndonat713** [Rbn3D/CustomCameraVPlus#5]
InertiaAffectsPitch dont disable camera move close to car

**Comment by Rbn3D** [comment]
InertiaAffectsPitch is only for look down when braking. This option will be removed in the next version, but I will add an option (InertiaForce) to set the desired ammount of inertia. Set to 0 to disable.

See latest commit https://github.com/Rbn3D/CustomCameraVPlus/commit/630ff51dc56641b873b13d4911b091a69d6787c4 from master, the option will be available in the next release.

**Comment by Rbn3D** [comment]
Closing this for now, feel free to reopen if needed.

**Comment by Rbn3D** [comment]
@sky0528 

The latest release [v1.7.0](https://github.com/Rbn3D/CustomCameraVPlus/releases/tag/v1.7.0) fixes this. Search for InertiaForce on the ini file and set it to desired ammount.
