### ISSUE TITLE
FreeLibrary should not be called

### ISSUE THREAD

**Issue by ikt32** [Rbn3D/CustomCameraVPlus#6]
https://github.com/Rbn3D/CustomCameraVPlus/blob/993a7ebd2d80258c29f5aaa051d9858c5a24043c/ManualTransmissionApi.cpp#L72

This can be removed, since the other dll was gotten with `GetModuleHandle`. You only need it when using `LoadLibrary`.

**Comment by Rbn3D** [comment]
So there is nothing to release, we can literally do nothing!

I was calling this on DllMain at detach time, I will remove this on the next update, make sure you update your Compatibily gist too!
