### ISSUE TITLE
Multicamera option?

### ISSUE THREAD

**Issue by mafradon** [Rbn3D/CustomCameraVPlus#7]
Hi, Would it be possible to create a multicamera view?

say i render the game in 7680x1080 (4 monitors) can i then create 4 views of 90 deg horizontal on each monitor? to create a 360 cube? 

would this be possible through scripthooking i ask myself.

**Comment by Rbn3D** [comment]
Hi,

Well, I think there is no way to render multiple cameras on the same frame on GTA V. 

It would probably require to hook the render pipeline itself and modify it, that sounds quite complex and is out of the scope of this project.

There is a mod called [R.E.A.L](https://github.com/LukeRoss00/gta5-real-mod) which does VR rendering (It's somehow related with what you want to achieve), but it does not render both eye images simultaneously, instead, it uses "alternate eye rendering", which basically updates one eye per frame. 

I agree that would be nice to have multicamera, but there is no way (AFAIK) to do it...

**Comment by Rbn3D** [comment]
Closing for now, feel free to comment/reopen if needed!
